news_list_frontend:
    path: /
    defaults: { _controller: 'App\Controller\NewsController::listFrontend' }
news_show:
    path: /news/{slug}
    defaults: { _controller: 'App\Controller\NewsController::show' }
